### ISSUE TITLE
When are you supporting Software PWM in android things?

### ISSUE THREAD

**Issue by imranbaig1977** [androidthings/native-libandroidthings#1]
It would really handy if you could bring in software PWM in Android things. 
Any plan for that?

Thanks
Imran

**Comment by proppy** [comment]
@imranbaig1977 this repository is for tracking issue around the native library distribution for Android Things.

For platform feature request, I'd recommend filing an issue on the [public issue tracker](https://b.corp.google.com/issues/new?component=192720&template=848805).
